Feature/pn 3013 spring boot 27
pagopa/pn-model pull request #99
Opened 2022-12-20 14:33 UTC by vincenzo-racca-pa

Passaggio a java 17 e Spring Boot 2.7.6. Eliminate dipendenze superflue.
Questa PR può essere mergiata SOLO dopo questa:
https://github.com/pagopa/pn-parent/pull/16

2022-12-21 17:44 UTC, MTurraPpa requested changes

2022-12-21 17:44 UTC, MTurraPpa commented on pom.xml
> +		<version>1.0.2-SNAPSHOT</version>
2.0.0-SNAPSHOT

2022-12-22 10:04 UTC, vincenzo-racca-pa commented on pom.xml
> +		<version>1.0.2-SNAPSHOT</version>
mergiato il branch develop dentro questo, quindi ora la versione di pn-model è 2.0.0-SNAPSHOT

2022-12-22 10:30 UTC, vincenzo-racca-pa commented on pom.xml
> +		<version>1.0.2-SNAPSHOT</version>
fatto

2022-12-22 13:56 UTC, merged